title: roff
description: Convert Unix man pages (roff/mdoc) to structured JSON or readable Markdown for docs pipelines and LLM context.
baseurl: "/roff"
url: "https://ljh-sh.github.io"

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled: true
  collections: true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
